### ISSUE TITLE
Import data from AusTraits

### ISSUE THREAD

**Issue by dfalster** [traitecoevo/australian_annuals#4]
Need to import data from AusTraits on life from. Suggest using public releases. We can access more complete data later when released. 

Please add code for loading into `Analysis.qmd`

@ehwenk or @dcol2804   - wondering if you do this?

**Comment by dcol2804** [comment]
Lizzy and I have written some code for this but I don't think I have write access to this repo yet?

**Comment by dfalster** [comment]
Great! Please fork and send a pull request.

**Comment by dfalster** [comment]
(forking makes a copy of the repo in your account, you can use this just like a branch. Github desktop might enable this too).

**Comment by dcol2804** [comment]
Ahh thanks for this, I just sent the pull request.

**Comment by dfalster** [comment]
Hi @dcol2804 - interesting, nothing has come through 

https://github.com/traitecoevo/australian_annuals/pulls

**Comment by dcol2804** [comment]
Ok, I see it there now

**Comment by dfalster** [comment]
Closed via #7
